### ISSUE TITLE
Implement The Edit Media Use Case

### ISSUE THREAD

**Issue by sebastien-deren** [sebastien-deren/Projet_6_snowtricks#16]
- [ ] Add Edit Media display to #8 
- [ ] Create a EditMedia Form and asserts(we may use #15 Form)
- [ ] Add EditMediaForm to FigureEditForm #8 (it might not be necessary if we use the same form for creation and edition)
- [ ] Update the Edit Figure Process to take into account the Media Collection added to an editedFigure
